### ISSUE TITLE
Usage in Jupyter notebook causes error

### ISSUE THREAD

**Issue by gyro-labs** [dcmvdbekerom/pypdfplot#49]
Hi,

I am encountering a FileNotFoundError when attempting to use the pypdfplot library in a Jupyter notebook. This issue arises when I try to save a matplotlib plot as a PDF. I've provided a minimal example below, along with the full error traceback for further insight.

**Minimal example:**
`main.ipynb`
```python
import pypdfplot.backend
import matplotlib.pyplot as plt

plt.figure()
plt.savefig('test_tmp.pdf')
```

**Error traceback:**
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In [4], [line 5](vscode-notebook-cell:?execution_count=4&line=5)
      [2](vscode-notebook-cell:?execution_count=4&line=2) import matplotlib.pyplot as plt
      [4](vscode-notebook-cell:?execution_count=4&line=4) plt.figure()
----> [5](vscode-notebook-cell:?execution_count=4&line=5) plt.savefig('test_tmp.pdf')

File [~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/pyplot.py:944](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/pyplot.py:944), in savefig(*args, **kwargs)
    [941](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/pyplot.py:941) @_copy_docstring_and_deprecators(Figure.savefig)
    [942](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/pyplot.py:942) def savefig(*args, **kwargs):
    [943](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/pyplot.py:943)     fig = gcf()
--> [944](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/pyplot.py:944)     res = fig.savefig(*args, **kwargs)
    [945](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/pyplot.py:945)     fig.canvas.draw_idle()  # Need this if 'transparent=True', to reset colors.
    [946](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/pyplot.py:946)     return res

File [~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/figure.py:3277](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/figure.py:3277), in Figure.savefig(self, fname, transparent, **kwargs)
   [3273](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/figure.py:3273)     for ax in self.axes:
   [3274](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/figure.py:3274)         stack.enter_context(
   [3275](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/figure.py:3275)             ax.patch._cm_set(facecolor='none', edgecolor='none'))
-> [3277](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/figure.py:3277) self.canvas.print_figure(fname, **kwargs)

File [~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/backend_bases.py:2338](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/backend_bases.py:2338), in FigureCanvasBase.print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)
   [2334](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/backend_bases.py:2334) try:
   [2335](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/backend_bases.py:2335)     # _get_renderer may change the figure dpi (as vector formats
   [2336](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/backend_bases.py:2336)     # force the figure dpi to 72), so we need to set it again here.
   [2337](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/backend_bases.py:2337)     with cbook._setattr_cm(self.figure, dpi=dpi):
-> [2338](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/backend_bases.py:2338)         result = print_method(
   [2339](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/backend_bases.py:2339)             filename,
   [2340](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/backend_bases.py:2340)             facecolor=facecolor,
   [2341](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/backend_bases.py:2341)             edgecolor=edgecolor,
   [2342](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/backend_bases.py:2342)             orientation=orientation,
   [2343](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/backend_bases.py:2343)             bbox_inches_restore=_bbox_inches_restore,
   [2344](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/backend_bases.py:2344)             **kwargs)
   [2345](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/backend_bases.py:2345) finally:
   [2346](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/backend_bases.py:2346)     if bbox_inches and restore_bbox:

File [~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/backend/backend_pypdf.py:41](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/backend/backend_pypdf.py:41), in print_pypdf(self, filename, dpi, bbox_inches_restore, metadata, **kwargs)
     [35](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/backend/backend_pypdf.py:35) def write_plot_func(fh,**kwargs):
     [36](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/backend/backend_pypdf.py:36)     print_pdf(self, fh, dpi=dpi,
     [37](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/backend/backend_pypdf.py:37)               bbox_inches_restore=bbox_inches_restore,
     [38](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/backend/backend_pypdf.py:38)               metadata=metadata,
     [39](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/backend/backend_pypdf.py:39)               **kwargs)
---> [41](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/backend/backend_pypdf.py:41) write_pypdf(write_plot_func,
     [42](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/backend/backend_pypdf.py:42)             output_fname = filename,
     [43](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/backend/backend_pypdf.py:43)             **kwargs)

File [~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/functions.py:266](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/functions.py:266), in write_pypdf(write_plot_func, output_fname, pack_list, cleanup, multiple, force_pickle, verbose, prompt_overwrite, **kwargs)
    [264](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/functions.py:264)     ## If input PyPDF file hasn't been read yet, do that now:
    [265](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/functions.py:265)     if _py_file == b_(''):
--> [266](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/functions.py:266)         _pypdf_fname = unpack()
    [268](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/functions.py:268) ## Add a page with the plot to the PyPPDF file:
    [269](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/functions.py:269) pickle_figure = (force_pickle if multiple != 'pickle' or _iteration == 0 else True)

File [~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/functions.py:45](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/functions.py:45), in unpack(fname, verbose)
     [42](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/functions.py:42) if fname == None:
     [43](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/functions.py:43)     fname = os.path.basename(sys.argv[0])
---> [45](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/functions.py:45) with open(fname,'rb') as fr:
     [46](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/functions.py:46)     #TO-DO: byte level operations should go to classes.py
     [47](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/functions.py:47)     read_buf = fr.read()
     [48](https://file+.vscode-resource.vscode-cdn.net/Users/mruijzendaal/Projects/UM/Software/projects/tmp/~/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/functions.py:48)     first1k = read_buf[:1024]

FileNotFoundError: [Errno 2] No such file or directory: 'ipykernel_launcher.py'
```

**Comment by mruijzendaal** [comment]
Perhaps this is a separate issue, but I observe the same when a Python script containing pypdfplot is executed from a different directory:

`./tmp/tmp2.py`
```python
import pypdfplot.backend
import matplotlib.pyplot as plt

plt.figure()
plt.savefig('test_tmp.pdf')
```

`python3 ./tmp/tmp2.py` yields
```
Preparing PyPDF file:
Traceback (most recent call last):
  File "/Users/mruijzendaal/Projects/UM/Software/projects/./tmp/tmp2.py", line 9, in <module>
    plt.savefig("example.pdf")
  File "/Users/mruijzendaal/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/pyplot.py", line 944, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/Users/mruijzendaal/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/figure.py", line 3277, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/Users/mruijzendaal/Projects/UM/Software/.venv/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2338, in print_figure
    result = print_method(
  File "/Users/mruijzendaal/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/backend/backend_pypdf.py", line 41, in print_pypdf
    write_pypdf(write_plot_func,
  File "/Users/mruijzendaal/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/functions.py", line 266, in write_pypdf
    _pypdf_fname = unpack()
  File "/Users/mruijzendaal/Projects/UM/Software/.venv/lib/python3.9/site-packages/pypdfplot/functions.py", line 45, in unpack
    with open(fname,'rb') as fr:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp2.py'
```
